# Generated by Django 6.0.3 on 2026-05-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=16)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userPassword', models.CharField(max_length=32)),
            ],
        ),
    ]
