# Generated by Django 6.0.3 on 2026-04-29 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userPassword',
        ),
    ]
