# Generated by Django 6.0.3 on 2026-05-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPassword',
            field=models.CharField(max_length=256),
        ),
    ]
