CAMPUS_BUILDINGS = [
    "Founders Building (FO)",
    "Cecil H. Green Hall (GR)",
    "Green Center (GC)",
    "SLC / Science Learning Center",
    "Sciences Building (SCI)",
    "Bioengineering and Sciences Building (BSB)",
    "Natural Science & Engineering Research Lab (NSERL)",
    "Engineering & Computer Science South (ECSS)",
    "Engineering & Computer Science West (ECSW)",
    "Engineering & Computer Science North (ECSN)",
    "Jonsson Engineering buildings (multiple ECS wings)",
    "Callier Center (Dallas + Richardson sites)",
    "Naveen Jindal School of Management (JSOM)",
    "Arts & Technology (ATEC)",
    "Visual Arts Building (SP/North side)",
    "Crow Museum of Asian Art (on campus)",
    "Student Union (SU)",
    "Student Services Building (SSB)",
    "Student Services Addition (SSA)",
    "Davidson-Gundy Alumni Center (DGA)",
    "Visitor Center (VCB)",
    "Administration Building",
    "Research Operations Center (ROC)",
    "Research Operations Center West (ROW)",
    "Synergy Park North (SPN)",
    "Synergy Park Central (SPC)",
    "Synergy Park South (SPS)",
    "Residence Hall North",
    "Residence Hall South",
    "Residence Hall Northwest",
    "Residence Hall Southwest",
    "Residence Hall West",
    "University Commons",
    "University Village Apartments (Buildings 1–67)",
    "Dining Hall West",
    "Dining Hall North",
    "Activity Center (AC)",
    "Recreation Center West (RCW)",
    "Parking Structure 1 (PS1)",
    "Parking Structure 3 (PS3)",
    "Parking Structure 4 (PS4)",
    "Parking garages + surface lots",
    "Police Department",
    "Bookstore / Comet Shop",
    "Eugene McDermott Library"
]
