# Generated by Django 6.0.3 on 2026-03-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='GameImages/')),
            ],
        ),
    ]
