# Generated by Django 6.0.3 on 2026-05-02 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('image_path', models.ImageField(upload_to='GameImages/')),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('game_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('gamemode', models.CharField(default='easy', max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
