# Generated by Django 6.0.3 on 2026-03-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameimage',
            name='image_id',
            field=models.IntegerField(default=0),
        ),
    ]
