# Generated by Django 6.0.3 on 2026-03-31 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameimage_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameimage',
            old_name='image',
            new_name='image_path',
        ),
    ]
