# Generated by Django 6.0.3 on 2026-04-22 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('game', '0003_rename_image_gameimage_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('game_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('gamemode', models.CharField(default='easy', max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
