# Generated by Django 6.0.3 on 2026-04-24 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('game', '0003_rename_image_gameimage_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('game_result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('difficult', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
