# Generated by Django 6.0.3 on 2026-04-25 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='date_played',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
