# Generated by Django 6.0.3 on 2026-04-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameresult_date_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameimage',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
